version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: english_platform_postgres
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - '${DATABASE_PORT}:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - english_platform_network

volumes:
  postgres_data:

networks:
  english_platform_network:
    driver: bridge
